version: '3.8'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_DATABASE

    ports:
      - 3306:3306

  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db